### ISSUE TITLE
Video Rotation Issue.

### ISSUE THREAD

**Issue by vivekCZ** [whydna/ReverseAVAsset#1]
I was working on video revrse from few days , And this is best I have seen yet. It really work like charms, but the only issue is that it rotates video at the end. Do you have any fix for this?

**Comment by whydna** [comment]
Hm, can you describe a bit more what you mean by "rotate the video at the end"? What is the file format for the video? If you take a look at the source, there are a few places where I've assumed .mp4, but this can easily be changed.

**Comment by vivekCZ** [comment]
when I reverse video from this line:

  AVAsset *reversedAsset = [AVUtilities assetByReversingAsset:originalAsset outputURL:exportUrl];

I got rotated video. I record video on portrait mode. And I checked reverse video in document folder it was in landscape mode. If you want to see original and reverse video then I can show you. This happen when I select video from galary or record from camera

**Comment by whydna** [comment]
What is the file format of the videos? Send them to me if you can.

**Comment by vivekCZ** [comment]
Hi, I got solution...I have applied transform.

[writerInput setTransform:[videoTrack preferredTransform]];

**Comment by albertgh** [comment]
@vivekCZ  Thank you so much. You saved my day.

**Comment by aiyub007** [comment]
hello.. I don't know Where to set this 

[writerInput setTransform:[videoTrack preferredTransform]];

My App is crashing If I am putting it like..
 [writer addInput:writerInput];
 [writer startWriting];
 [writerInput setTransform:[videoTrack preferredTransform]];

**Comment by aiyub007** [comment]
resolved......
[writer startWriting];
[writer addInput:writerInput];
[writerInput setTransform:[videoTrack preferredTransform]];

**Comment by ramabhi777** [comment]
hi vivek 
           i am trying to use it in swift 3 using objective c files but i am noting getting reverse Assest: - 
       
       i am using this code and new assest playing in screcorder player but it still playing origional video.

           let newAssest = AVUtilities.asset(byReversing: videoAsset, outputURL: videoUrl1)
           player!.setItemBy(newAssest)
          self.player!.play()

Thanks 
punit chauhan
