### ISSUE TITLE
I am getting this error,please help. 

### ISSUE THREAD

**Issue by harminderjarvics** [whydna/ReverseAVAsset#5]
> 2016-10-03 12:46:04.855190 360Image[1816:354093] **\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '**\* -[AVAssetReaderTrackOutput initWithTrack:outputSettings:] invalid parameter not satisfying: track != ((void _)0)'
> *_\* First throw call stack:
> (0x1f491e07 0x1e6f7077 0x25b6a4bd 0x25b6a097 0x101f1b 0xfe037 0xe47d67 0xe47d53 0xe4c5f1 0x1f44da17 0x1f44bcff 0x1f39b073 0x1f39ae81 0x20b43bfd 0x24542acf 0x2453d201 0x10c301 0x1eb6650b)
> libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by harminderjarvics** [comment]
It doesn't even reads the video.  AVAssetReader is always nil,maybe that is why i am getting the above error. I have tried everything but does't work.

**Comment by wangruocong** [comment]
same issue, any idea?

**Comment by wangruocong** [comment]
I  solved this problem by use fileURLWithPath


 NSString *videoPath =  @"/Users/username/Desktop/sample.mov";
 NSURL *videoUrl = [NSURL fileURLWithPath:videoPath];

url is not fileURL type will cause problem.
