### ISSUE TITLE
The direction of the video has changed?

### ISSUE THREAD

**Issue by qq245124008** [whydna/ReverseAVAsset#8]
After editing,The direction of the video has changed?

**Comment by qq245124008** [comment]
and After editing, the original sound of the video was gone

**Comment by qq245124008** [comment]
What can I do to make voice added and is played backwards.

**Comment by whydna** [comment]
@qq245124008 the code sample here only performs for the video track. If you want to reverse the sound as well, you will need to do the same thing for the audio tracks as well.
